const pokemons = [
    {
        abilities: ['Overgrow'],
        detailPageURL: '/us/pokedex/bulbasaur',
        weight: 15.2,
        weakness: ['Fire', 'Psychic', 'Flying', 'Ice'],
        number: '0001',
        height: 28.0,
        collectibles_slug: 'bulbasaur',
        featured: 'true',
        slug: 'bulbasaur',
        name: 'Bulbasaur',
        ThumbnailAltText: 'Bulbasaur',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png',
        id: 1,
        type: ['grass', 'poison'],
        description: 'A small and seed-bearing Pokémon, thrives with the Overgrow ability. Its grass and poison typing make it adept in varied environments, although its particularly vulnerable to fire, psychic, flying, and ice attacks.',
    },
    {
        abilities: ['Overgrow'],
        detailPageURL: '/us/pokedex/ivysaur',
        weight: 28.7,
        weakness: ['Fire', 'Psychic', 'Flying', 'Ice'],
        number: '0002',
        height: 39.0,
        collectibles_slug: 'ivysaur',
        featured: 'true',
        slug: 'ivysaur',
        name: 'Ivysaur',
        ThumbnailAltText: 'Ivysaur',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png',
        id: 2,
        type: ['grass', 'poison'],
        description: 'The evolved form of Bulbasaur, maintains its Overgrow ability. This Pokémons evolution brings heightened abilities and resilience. Its dual grass and poison typing continue to excel in diverse habitats, although it remains weak against fire, psychic, flying, and ice attacks.',
    },
    {
        abilities: ['Overgrow'],
        detailPageURL: '/us/pokedex/venusaur',
        weight: 9999.0,
        weakness: ['Fire', 'Psychic', 'Flying', 'Ice'],
        number: '0003',
        height: 945.0,
        collectibles_slug: 'venusaur',
        featured: 'true',
        slug: 'venusaur',
        name: 'Venusaur',
        ThumbnailAltText: 'Venusaur',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png',
        id: 3,
        type: ['grass', 'poison'],
        description: 'The final evolution of the Bulbasaur line, retains the Overgrow ability. Towering in size, this Pokémon commands the environment with its immense stature and powerful abilities. Its grass and poison typing enable it to flourish across various landscapes, yet it remains susceptible to fire, psychic, flying, and ice attacks.',
    },
    {
        abilities: ['Thick Fat'],
        detailPageURL: '/us/pokedex/venusaur',
        weight: 342.8,
        weakness: ['Fire', 'Psychic', 'Flying', 'Ice'],
        number: '0003',
        height: 94.0,
        collectibles_slug: 'venusaur',
        featured: 'true',
        slug: 'venusaur',
        name: 'Venusaur',
        ThumbnailAltText: 'Venusaur',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png',
        id: 3,
        type: ['grass', 'poison'],
        description: 'An alternate form with Thick Fat ability, alters its strategies by leveraging its increased bulk against opponents. Its adaptable nature and grass-poison typing still uphold a versatile approach, though it remains vulnerable to fire, psychic, flying, and ice attacks.',
    },
    {
        abilities: ['Overgrow'],
        detailPageURL: '/us/pokedex/venusaur',
        weight: 220.5,
        weakness: ['Fire', 'Psychic', 'Flying', 'Ice'],
        number: '0003',
        height: 79.0,
        collectibles_slug: 'venusaur',
        featured: 'true',
        slug: 'venusaur',
        name: 'Venusaur',
        ThumbnailAltText: 'Venusaur',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png',
        id: 3,
        type: ['grass', 'poison'],
        description: 'Another variant, maintains the Overgrow ability, showcasing agility despite a slightly different physical build. Its grass and poison typing allows it to adapt across various terrains, yet it remains prone to fire, psychic, flying, and ice attacks.',
    },
    {
        abilities: ['Blaze'],
        detailPageURL: '/us/pokedex/charmander',
        weight: 18.7,
        weakness: ['Water', 'Ground', 'Rock'],
        number: '0004',
        height: 24.0,
        collectibles_slug: 'charmander',
        featured: 'true',
        slug: 'charmander',
        name: 'Charmander',
        ThumbnailAltText: 'Charmander',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png',
        id: 4,
        type: ['fire'],
        description: 'A flame-tailed Pokémon with the Blaze ability, symbolizes fiery potential. Its fire typing imbues it with scorching capabilities, yet it remains vulnerable to water, ground, and rock-based attacks.',
    },
    {
        abilities: ['Blaze'],
        detailPageURL: '/us/pokedex/charmeleon',
        weight: 41.9,
        weakness: ['Water', 'Ground', 'Rock'],
        number: '0005',
        height: 43.0,
        collectibles_slug: 'charmeleon',
        featured: 'true',
        slug: 'charmeleon',
        name: 'Charmeleon',
        ThumbnailAltText: 'Charmeleon',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png',
        id: 5,
        type: ['fire'],
        description: 'The evolved form of Charmander, sustains the Blaze ability, furthering its mastery over flames. Its prowess in fire attacks grows, yet it continues to be susceptible to water, ground, and rock-based attacks.',
    },
    {
        abilities: ['Blaze'],
        detailPageURL: '/us/pokedex/charizard',
        weight: 9999.0,
        weakness: ['Water', 'Electric', 'Rock'],
        number: '0006',
        height: 1102.0,
        collectibles_slug: 'charizard',
        featured: 'true',
        slug: 'charizard',
        name: 'Charizard',
        ThumbnailAltText: 'Charizard',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png',
        id: 6,
        type: ['fire', 'flying'],
        description: 'The final evolution of Charmanders line, wields the Blaze ability alongside the added power of flight. Its fire and flying typing bestows it with incredible versatility, yet it remains vulnerable to water, electric, and rock-based attacks.',
    },
    {
        abilities: ['Drought'],
        detailPageURL: '/us/pokedex/charizard',
        weight: 221.6,
        weakness: ['Water', 'Electric', 'Rock'],
        number: '0006',
        height: 67.0,
        collectibles_slug: 'charizard',
        featured: 'true',
        slug: 'charizard',
        name: 'Charizard',
        ThumbnailAltText: 'Charizard',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png',
        id: 6,
        type: ['fire', 'flying'],
        description: 'With the alternate Drought ability, commands the skies with enhanced fire abilities. Its dual fire and flying typing grants it dominion over aerial battles, although it remains susceptible to water, electric, and rock-based attacks.',
    },
    {
        abilities: ['Tough Claws'],
        detailPageURL: '/us/pokedex/charizard',
        weight: 243.6,
        weakness: ['Ground', 'Rock', 'Dragon'],
        number: '0006',
        height: 67.0,
        collectibles_slug: 'charizard',
        featured: 'true',
        slug: 'charizard',
        name: 'Charizard',
        ThumbnailAltText: 'Charizard',
        ThumbnailImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png',
        id: 6,
        type: ['fire', 'dragon', 'flying'],
        description: 'Its final variant, harnesses the Tough Claws ability, bolstering its physical attacks and introducing a dragon aspect to its typing. Its fire, dragon, and flying capabilities ensure a formidable presence, despite remaining vulnerable to ground, rock, and dragon-type attacks.',
    },
];

export default pokemons;
